name: 'Deploy Infra'
on:
  push:
    branches:
      - main
jobs:
  deploy-to-azure:
    name: 'Deploy to Azure'
    runs-on: ubuntu-latest
    steps:

      - name: 'Checkout'
        uses: actions/checkout@master
      
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.1.2

      - name: "Login via Azure CLI"
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy code
        uses: azure/CLI@v1
        with:
          inlineScript: |
              terraform init && terraform apply --auto-approve

