name: 'Deploy Infra'
on:
  push:
    branches:
      - main
jobs:
  deploy-to-azure:
    name: 'Deploy to Azure'
    env:
      ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@master

      - name: 'Terraform Init'
        uses: hashicorp/terraform-github-actions@master
        with:
<<<<<<< HEAD
          tf_actions_version: 0.12.24
          tf_actions_subcommand: 'init'
          tf_actions_working_dir: "./terraform"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
=======
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          
      - run: |
          az account show
>>>>>>> refs/remotes/origin/main

      - name: 'Terraform Apply'
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: 0.12.24
          tf_actions_subcommand: 'apply'
          tf_actions_working_dir: "./terraform"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}